---
language: node_js
node_js: stable
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.npm

env:
  global:
    - JOBS=1

jobs:
  include:
    - stage: test
    - stage: "Release"
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

before_install:
  - npm config set spin false
  - npm install -g npm@6
  - npm install -g codecov
  - npm install -g greenkeeper-lockfile@1
  - npm install -g @commitlint/travis-cli
  - npm --version

install:
  - if [[ $TRAVIS_BRANCH =~ greenkeeper || $TRAVIS_PULL_REQUEST_BRANCH =~ greenkeeper ]]; then npm install; else npm ci; fi

before_script:
  - greenkeeper-lockfile-update

script:
  - commitlint-travis
  - npm run lint:js
  - npm test

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - codecov --file=coverage/lcov.info

stages:
  - test
  - name: "Release"
    if: branch = master
